#ifndef __SRC_PARROT_SRC_PLATFORM_OS_VIDEO_PLATFORM_H_
#define __SRC_PARROT_SRC_PLATFORM_OS_VIDEO_PLATFORM_H_

typedef struct ParrotVideoGLContext ParrotVideoGLContext;

ParrotVideoGLContext *ParrotVideoGLContext_new(void);
void ParrotVideoGLContext_delete(ParrotVideoGLContext *self);

void ParrotVideoGLContext_make_current(ParrotVideoGLContext *self);

#endif // __SRC_PARROT_SRC_PLATFORM_OS_VIDEO_PLATFORM_H_