include $(PLATFORM_DIR)/default_config.mk
-include $(PLATFORM_DIR)/config.mk

SRCS ?=

CFLAGS += $(PUBLIC_CFLAGS) $(PRIVATE_CFLAGS)
CFLAGS += -DPARROT_PLATFORM_LINUX

ifeq ($(DEBUG_INFO),1)
CFLAGS += -g
endif

ifeq ($(OPTIMIZE),1)
CFLAGS += $(OPTIMIZER)
endif

OUTPUT_STATIC=$(BUILD_DIR)/$(OUTPUT_NAME).a
OUTPUT_SHARED=$(BUILD_DIR)/$(OUTPUT_NAME).so

OUTPUT_MODULE_NAME=module.txt
OUTPUT_MODULE=$(BUILD_DIR)/$(OUTPUT_MODULE_NAME)
